// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/apis/auth_service.proto

package apis

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuthStartRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthStartRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthStartRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthStartRequestMultiError, or nil if none found.
func (m *AuthStartRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthStartRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthStartRequestMultiError(errors)
	}

	return nil
}

// AuthStartRequestMultiError is an error wrapping multiple validation errors
// returned by AuthStartRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthStartRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthStartRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthStartRequestMultiError) AllErrors() []error { return m }

// AuthStartRequestValidationError is the validation error returned by
// AuthStartRequest.Validate if the designated constraints aren't met.
type AuthStartRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthStartRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthStartRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthStartRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthStartRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthStartRequestValidationError) ErrorName() string { return "AuthStartRequestValidationError" }

// Error satisfies the builtin error interface
func (e AuthStartRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthStartRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthStartRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthStartRequestValidationError{}

// Validate checks the field values on AuthStartResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthStartResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthStartResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthStartResponseMultiError, or nil if none found.
func (m *AuthStartResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthStartResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Message

	if len(errors) > 0 {
		return AuthStartResponseMultiError(errors)
	}

	return nil
}

// AuthStartResponseMultiError is an error wrapping multiple validation errors
// returned by AuthStartResponse.ValidateAll() if the designated constraints
// aren't met.
type AuthStartResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthStartResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthStartResponseMultiError) AllErrors() []error { return m }

// AuthStartResponseValidationError is the validation error returned by
// AuthStartResponse.Validate if the designated constraints aren't met.
type AuthStartResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthStartResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthStartResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthStartResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthStartResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthStartResponseValidationError) ErrorName() string {
	return "AuthStartResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthStartResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthStartResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthStartResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthStartResponseValidationError{}
