// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: healthcheck/apis/health_service.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status indicates the health status of the service.
type CheckHealthServiceResponse_Status int32

const (
	CheckHealthServiceResponse_STATUS_UNSPECIFIED CheckHealthServiceResponse_Status = 0 // Health status unknown
	CheckHealthServiceResponse_STATUS_UNKNOWN     CheckHealthServiceResponse_Status = 1 // Health status unknown
	CheckHealthServiceResponse_STATUS_HEALTHY     CheckHealthServiceResponse_Status = 2 // Service is healthy
	CheckHealthServiceResponse_STATUS_UNHEALTHY   CheckHealthServiceResponse_Status = 3 // Service is unhealthy
)

// Enum value maps for CheckHealthServiceResponse_Status.
var (
	CheckHealthServiceResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UNKNOWN",
		2: "STATUS_HEALTHY",
		3: "STATUS_UNHEALTHY",
	}
	CheckHealthServiceResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_UNKNOWN":     1,
		"STATUS_HEALTHY":     2,
		"STATUS_UNHEALTHY":   3,
	}
)

func (x CheckHealthServiceResponse_Status) Enum() *CheckHealthServiceResponse_Status {
	p := new(CheckHealthServiceResponse_Status)
	*p = x
	return p
}

func (x CheckHealthServiceResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckHealthServiceResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_healthcheck_apis_health_service_proto_enumTypes[0].Descriptor()
}

func (CheckHealthServiceResponse_Status) Type() protoreflect.EnumType {
	return &file_healthcheck_apis_health_service_proto_enumTypes[0]
}

func (x CheckHealthServiceResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckHealthServiceResponse_Status.Descriptor instead.
func (CheckHealthServiceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_healthcheck_apis_health_service_proto_rawDescGZIP(), []int{1, 0}
}

// HealthCheckRequest represents a request to check the health of a service.
type CheckHealthServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckHealthServiceRequest) Reset() {
	*x = CheckHealthServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthcheck_apis_health_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHealthServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthServiceRequest) ProtoMessage() {}

func (x *CheckHealthServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_apis_health_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthServiceRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthServiceRequest) Descriptor() ([]byte, []int) {
	return file_healthcheck_apis_health_service_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse represents a response indicating the health status of a service.
type CheckHealthServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Status of the service.
	Status CheckHealthServiceResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=healthcheck.apis.CheckHealthServiceResponse_Status" json:"status,omitempty"`
	// Additional details or error messages can be included here.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CheckHealthServiceResponse) Reset() {
	*x = CheckHealthServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthcheck_apis_health_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHealthServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthServiceResponse) ProtoMessage() {}

func (x *CheckHealthServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_apis_health_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthServiceResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthServiceResponse) Descriptor() ([]byte, []int) {
	return file_healthcheck_apis_health_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckHealthServiceResponse) GetStatus() CheckHealthServiceResponse_Status {
	if x != nil {
		return x.Status
	}
	return CheckHealthServiceResponse_STATUS_UNSPECIFIED
}

func (x *CheckHealthServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_healthcheck_apis_health_service_proto protoreflect.FileDescriptor

var file_healthcheck_apis_health_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe3, 0x01, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5e, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x48, 0x45, 0x41,
	0x4c, 0x54, 0x48, 0x59, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x03, 0x32, 0x87, 0x01, 0x0a,
	0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x71, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x2e, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xa9, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x42,
	0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x1a, 0x62, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0xa2, 0x02, 0x03, 0x48, 0x41, 0x58, 0xaa, 0x02, 0x10, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x41, 0x70, 0x69, 0x73, 0xca, 0x02, 0x10, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5c, 0x41, 0x70, 0x69, 0x73, 0xe2,
	0x02, 0x1c, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5c, 0x41, 0x70,
	0x69, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x11, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x3a, 0x3a, 0x41, 0x70,
	0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_healthcheck_apis_health_service_proto_rawDescOnce sync.Once
	file_healthcheck_apis_health_service_proto_rawDescData = file_healthcheck_apis_health_service_proto_rawDesc
)

func file_healthcheck_apis_health_service_proto_rawDescGZIP() []byte {
	file_healthcheck_apis_health_service_proto_rawDescOnce.Do(func() {
		file_healthcheck_apis_health_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_healthcheck_apis_health_service_proto_rawDescData)
	})
	return file_healthcheck_apis_health_service_proto_rawDescData
}

var file_healthcheck_apis_health_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_healthcheck_apis_health_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_healthcheck_apis_health_service_proto_goTypes = []interface{}{
	(CheckHealthServiceResponse_Status)(0), // 0: healthcheck.apis.CheckHealthServiceResponse.Status
	(*CheckHealthServiceRequest)(nil),      // 1: healthcheck.apis.CheckHealthServiceRequest
	(*CheckHealthServiceResponse)(nil),     // 2: healthcheck.apis.CheckHealthServiceResponse
}
var file_healthcheck_apis_health_service_proto_depIdxs = []int32{
	0, // 0: healthcheck.apis.CheckHealthServiceResponse.status:type_name -> healthcheck.apis.CheckHealthServiceResponse.Status
	1, // 1: healthcheck.apis.HealthCheckService.CheckHealthService:input_type -> healthcheck.apis.CheckHealthServiceRequest
	2, // 2: healthcheck.apis.HealthCheckService.CheckHealthService:output_type -> healthcheck.apis.CheckHealthServiceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_healthcheck_apis_health_service_proto_init() }
func file_healthcheck_apis_health_service_proto_init() {
	if File_healthcheck_apis_health_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_healthcheck_apis_health_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHealthServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_healthcheck_apis_health_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHealthServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_healthcheck_apis_health_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthcheck_apis_health_service_proto_goTypes,
		DependencyIndexes: file_healthcheck_apis_health_service_proto_depIdxs,
		EnumInfos:         file_healthcheck_apis_health_service_proto_enumTypes,
		MessageInfos:      file_healthcheck_apis_health_service_proto_msgTypes,
	}.Build()
	File_healthcheck_apis_health_service_proto = out.File
	file_healthcheck_apis_health_service_proto_rawDesc = nil
	file_healthcheck_apis_health_service_proto_goTypes = nil
	file_healthcheck_apis_health_service_proto_depIdxs = nil
}
