// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: healthcheck/apis/health_service.proto

package apis

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CheckHealthServiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckHealthServiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckHealthServiceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckHealthServiceRequestMultiError, or nil if none found.
func (m *CheckHealthServiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckHealthServiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CheckHealthServiceRequestMultiError(errors)
	}

	return nil
}

// CheckHealthServiceRequestMultiError is an error wrapping multiple validation
// errors returned by CheckHealthServiceRequest.ValidateAll() if the
// designated constraints aren't met.
type CheckHealthServiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckHealthServiceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckHealthServiceRequestMultiError) AllErrors() []error { return m }

// CheckHealthServiceRequestValidationError is the validation error returned by
// CheckHealthServiceRequest.Validate if the designated constraints aren't met.
type CheckHealthServiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckHealthServiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckHealthServiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckHealthServiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckHealthServiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckHealthServiceRequestValidationError) ErrorName() string {
	return "CheckHealthServiceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckHealthServiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckHealthServiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckHealthServiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckHealthServiceRequestValidationError{}

// Validate checks the field values on CheckHealthServiceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckHealthServiceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckHealthServiceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckHealthServiceResponseMultiError, or nil if none found.
func (m *CheckHealthServiceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckHealthServiceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Message

	if len(errors) > 0 {
		return CheckHealthServiceResponseMultiError(errors)
	}

	return nil
}

// CheckHealthServiceResponseMultiError is an error wrapping multiple
// validation errors returned by CheckHealthServiceResponse.ValidateAll() if
// the designated constraints aren't met.
type CheckHealthServiceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckHealthServiceResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckHealthServiceResponseMultiError) AllErrors() []error { return m }

// CheckHealthServiceResponseValidationError is the validation error returned
// by CheckHealthServiceResponse.Validate if the designated constraints aren't met.
type CheckHealthServiceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckHealthServiceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckHealthServiceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckHealthServiceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckHealthServiceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckHealthServiceResponseValidationError) ErrorName() string {
	return "CheckHealthServiceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CheckHealthServiceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckHealthServiceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckHealthServiceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckHealthServiceResponseValidationError{}
